# Generated by Django 5.2 on 2025-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25)),
                ('rdate', models.DateField()),
                ('ssmry', models.TextField()),
                ('issues', models.TextField()),
                ('update', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
