# Generated by Django 5.2 on 2025-05-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='toy_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=25)),
                ('tprc', models.IntegerField()),
                ('timg', models.FileField(upload_to='pic')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='mob',
            field=models.CharField(max_length=16),
        ),
    ]
